#!/bin/bash
out_folder=./out/
if ! [ -e "$out_folder" ]; then
	echo dirrectory "$out_folder" does not exist
	echo please create this directory or edit "$0"
	exit 0
fi
g++ "$@".cpp -Wall -Wextra -Werror -pedantic -std=c++20 -o ./out/"$@".out
echo compiled[+]
read -p "Do you want to run the program?[y/n]: " a
if [[ "$a" == "y" ]]; then
	./out/"$@".out
fi
echo

