#!/bin/bash
if [[ "$2" == "-o" ]]; then
	if [[ "$2" == "-o" ]]; then
		out_folder="$3"
	fi
else
	out_folder=./out/
	if ! [ -e "$out_folder" ]; then
		echo dirrectory "$out_folder" does not exist
		echo please create this directory or edit "$0"
		exit 0
	fi
	out_folder=./out/"$1".out
fi

g++ "$1".cpp -Wall -Wextra -Werror -pedantic -std=c++20 -o "$out_folder"

is_compiled=$?
if [ "$is_compiled" != "0" ]; then
	echo compilation failed[-]
	exit 0
fi
echo compiled[+]
read -p "Do you want to run the program?[y/n]: " a
if [[ "$a" == "y" ]]; then
	./"$out_folder"
fi
echo
